name: fulltextrss-base

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 00:00 on Sunday.
    # https://crontab.guru/#0_0_*_*_7
    - cron:  '30 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
        docker build -f ${PROJECT}/Dockerfile -t ${CONTAINER_IMAGE} .
      env:
        PROJECT: ${{ github.workflow }}
        CONTAINER_IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.workflow }}:${{ github.sha }}
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        docker push ${CONTAINER_IMAGE}
