name: mysql

on:
  push:
    paths:
      - ".github/workflows/mysql.yml"
      - "mysql/**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 00:00 on Sunday.
    # https://crontab.guru/#0_0_*_*_7
    - cron: "30 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql-version:
          - "5.7.30"
        percona-extrabackup-pkg-name:
          - "percona-xtrabackup-24"
    steps:
      - name: Env
        run: |
          env | sort
      - uses: actions/checkout@master
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Handle keyserver connections
        run: |
          wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
      - name: Generate Dockerfile
        run: |
          cat ${PROJECT}/Dockerfile.template | docker run -i --rm subfuzion/envtpl > ${PROJECT}/Dockerfile ;
        env:
          PROJECT: ${{ github.workflow }}
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          repository: ${{ github.repository_owner}}/${{ github.workflow }}
          dockerfile: ${{ github.workflow }}/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_ANDROMEDARABBIT }}
          tags: "latest"
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
